server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
      register-with-eureka: false
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
spring:
  application:
    name: userconsumer
user-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
