server:
  port: 8888
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    druid:
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false
      username: root
      password: root
  application:
    name: user-service
mybatis:
  typeAliasesPackage: com.entity
  mapperLocations: classpath:mapper/*.xml
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
